/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Customer {
  'id' : CustomerId,
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type CustomerId = string;
export interface Product {
  'id' : ProductId,
  'name' : string,
  'description' : string,
  'quantity' : bigint,
  'price' : number,
}
export type ProductId = string;
export interface Quote {
  'id' : QuoteId,
  'tax' : number,
  'customerName' : string,
  'lineItems' : Array<QuoteLineItem>,
  'created' : bigint,
  'total' : number,
  'customerId' : CustomerId,
  'subtotal' : number,
}
export type QuoteId = bigint;
export interface QuoteLineItem {
  'total' : number,
  'productId' : ProductId,
  'productName' : string,
  'quantity' : bigint,
  'unitPrice' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adjustProductStock' : ActorMethod<[ProductId, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCustomer' : ActorMethod<[Customer], undefined>,
  'createProduct' : ActorMethod<[Product], undefined>,
  'createQuote' : ActorMethod<[CustomerId, Array<QuoteLineItem>], Quote>,
  'deleteCustomer' : ActorMethod<[CustomerId], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[CustomerId], Customer>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getQuote' : ActorMethod<[QuoteId], Quote>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCustomers' : ActorMethod<[], Array<Customer>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'listQuotes' : ActorMethod<[], Array<Quote>>,
  'listQuotesByCustomer' : ActorMethod<[CustomerId], Array<Quote>>,
  'updateCustomer' : ActorMethod<[Customer], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];