/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CustomerId = IDL.Text;
export const Customer = IDL.Record({
  'id' : CustomerId,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
});
export const QuoteLineItem = IDL.Record({
  'total' : IDL.Float64,
  'productId' : ProductId,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Float64,
});
export const QuoteId = IDL.Nat;
export const Quote = IDL.Record({
  'id' : QuoteId,
  'tax' : IDL.Float64,
  'customerName' : IDL.Text,
  'lineItems' : IDL.Vec(QuoteLineItem),
  'created' : IDL.Int,
  'total' : IDL.Float64,
  'customerId' : CustomerId,
  'subtotal' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adjustProductStock' : IDL.Func([ProductId, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCustomer' : IDL.Func([Customer], [], []),
  'createProduct' : IDL.Func([Product], [], []),
  'createQuote' : IDL.Func([CustomerId, IDL.Vec(QuoteLineItem)], [Quote], []),
  'deleteCustomer' : IDL.Func([CustomerId], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([CustomerId], [Customer], ['query']),
  'getProduct' : IDL.Func([ProductId], [Product], ['query']),
  'getQuote' : IDL.Func([QuoteId], [Quote], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listQuotes' : IDL.Func([], [IDL.Vec(Quote)], ['query']),
  'listQuotesByCustomer' : IDL.Func([CustomerId], [IDL.Vec(Quote)], ['query']),
  'updateCustomer' : IDL.Func([Customer], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CustomerId = IDL.Text;
  const Customer = IDL.Record({
    'id' : CustomerId,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
  });
  const QuoteLineItem = IDL.Record({
    'total' : IDL.Float64,
    'productId' : ProductId,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Float64,
  });
  const QuoteId = IDL.Nat;
  const Quote = IDL.Record({
    'id' : QuoteId,
    'tax' : IDL.Float64,
    'customerName' : IDL.Text,
    'lineItems' : IDL.Vec(QuoteLineItem),
    'created' : IDL.Int,
    'total' : IDL.Float64,
    'customerId' : CustomerId,
    'subtotal' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adjustProductStock' : IDL.Func([ProductId, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCustomer' : IDL.Func([Customer], [], []),
    'createProduct' : IDL.Func([Product], [], []),
    'createQuote' : IDL.Func([CustomerId, IDL.Vec(QuoteLineItem)], [Quote], []),
    'deleteCustomer' : IDL.Func([CustomerId], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([CustomerId], [Customer], ['query']),
    'getProduct' : IDL.Func([ProductId], [Product], ['query']),
    'getQuote' : IDL.Func([QuoteId], [Quote], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listQuotes' : IDL.Func([], [IDL.Vec(Quote)], ['query']),
    'listQuotesByCustomer' : IDL.Func(
        [CustomerId],
        [IDL.Vec(Quote)],
        ['query'],
      ),
    'updateCustomer' : IDL.Func([Customer], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };